// auth-react/src/pages/Login.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';

const Login = () => {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [message, setMessage] = useState('');
    const [loading, setLoading] = useState(false);
    const navigate = useNavigate();

    const handleLogin = async (e) => {
        e.preventDefault();
        setLoading(true);
        try {
            // Vérifie si l'utilisateur existe dans le JSON Server
            const response = await axios.get(`http://localhost:5000/users?email=${email}&password=${password}`);
            if (response.data.length > 0) {
                // Utilisateur trouvé : sauvegarde dans localStorage et redirige vers Home
                localStorage.setItem('token', JSON.stringify(response.data[0]));
                navigate('/home');
            } else {
                setMessage('Email ou mot de passe incorrect.');
            }
        } catch (error) {
            setMessage('Erreur lors de la connexion.');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="login-container">
            <div className="login-card">
                <div className="login-header">
                    <h2>Connexion</h2>
                    <p className="subtitle">Connectez-vous pour accéder à votre compte</p>
                </div>

                {message && (
                    <div className="message error">
                        {message}
                    </div>
                )}

                <form onSubmit={handleLogin}>
                    <div className="form-group">
                        <label htmlFor="email">Email</label>
                        <input
                            id="email"
                            type="email"
                            placeholder="Votre adresse email"
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            required
                        />
                    </div>

                    <div className="form-group">
                        <label htmlFor="password">Mot de passe</label>
                        <input
                            id="password"
                            type="password"
                            placeholder="Votre mot de passe"
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            required
                        />
                    </div>

                    <div className="forgot-password">
                        <a href="/forgot-password">Mot de passe oublié ?</a>
                    </div>

                    <button
                        type="submit"
                        className={`login-button ${loading ? 'loading' : ''}`}
                        disabled={loading}
                    >
                        {loading ? (
                            <span className="loading-spinner"></span>
                        ) : (
                            "Se connecter"
                        )}
                    </button>
                </form>

                <div className="signup-link">
                    Nouveau ici ? <a href="/signup">Créez un compte</a>
                </div>
            </div>

            <style jsx>{`
                .login-container {
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    min-height: 100vh;
                    background-color: #f5f7fa;
                    padding: 20px;
                    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                }
                
                .login-card {
                    width: 100%;
                    max-width: 450px;
                    background: white;
                    border-radius: 12px;
                    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.08);
                    padding: 40px;
                    transition: transform 0.2s ease;
                }
                
                .login-card:hover {
                    transform: translateY(-5px);
                }
                
                .login-header {
                    text-align: center;
                    margin-bottom: 32px;
                }
                
                .login-header h2 {
                    margin: 0;
                    color: #111827;
                    font-size: 24px;
                    font-weight: 700;
                }
                
                .subtitle {
                    color: #6b7280;
                    font-size: 14px;
                    margin-top: 8px;
                }
                
                .form-group {
                    margin-bottom: 20px;
                }
                
                label {
                    display: block;
                    margin-bottom: 6px;
                    font-size: 14px;
                    font-weight: 500;
                    color: #374151;
                }
                
                input {
                    width: 100%;
                    padding: 12px 16px;
                    border: 1px solid #d1d5db;
                    border-radius: 8px;
                    font-size: 15px;
                    transition: all 0.2s ease;
                    background-color: #f9fafb;
                    height: 48px;
                    box-sizing: border-box;
                }
                
                input:focus {
                    outline: none;
                    border-color: #4f46e5;
                    box-shadow: 0 0 0 3px rgba(79, 70, 229, 0.1);
                    background-color: white;
                }
                
                input::placeholder {
                    color: #9ca3af;
                    font-size: 14px;
                }
                
                .forgot-password {
                    text-align: right;
                    margin-bottom: 20px;
                }
                
                .forgot-password a {
                    font-size: 13px;
                    color: #4f46e5;
                    text-decoration: none;
                    transition: color 0.2s ease;
                }
                
                .forgot-password a:hover {
                    color: #4338ca;
                    text-decoration: underline;
                }
                
                .login-button {
                    width: 100%;
                    padding: 12px;
                    background-color: #4f46e5;
                    color: white;
                    border: none;
                    border-radius: 8px;
                    font-size: 16px;
                    font-weight: 500;
                    cursor: pointer;
                    transition: all 0.2s ease;
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    height: 48px;
                }
                
                .login-button:hover {
                    background-color: #4338ca;
                    transform: translateY(-1px);
                }
                
                .login-button:active {
                    transform: translateY(1px);
                }
                
                .login-button.loading {
                    background-color: #6366f1;
                    cursor: not-allowed;
                }
                
                .loading-spinner {
                    display: inline-block;
                    width: 20px;
                    height: 20px;
                    border: 3px solid rgba(255, 255, 255, 0.3);
                    border-radius: 50%;
                    border-top-color: white;
                    animation: spin 1s ease-in-out infinite;
                }
                
                @keyframes spin {
                    to { transform: rotate(360deg); }
                }
                
                .signup-link {
                    text-align: center;
                    margin-top: 24px;
                    font-size: 14px;
                    color: #6b7280;
                }
                
                .signup-link a {
                    color: #4f46e5;
                    text-decoration: none;
                    font-weight: 500;
                    transition: color 0.2s ease;
                }
                
                .signup-link a:hover {
                    color: #4338ca;
                    text-decoration: underline;
                }
                
                .message {
                    padding: 12px 16px;
                    border-radius: 8px;
                    margin-bottom: 24px;
                    font-size: 14px;
                    animation: fadeIn 0.3s ease;
                }
                
                .error {
                    background-color: #fef2f2;
                    color: #b91c1c;
                    border: 1px solid #fecaca;
                }
                
                @keyframes fadeIn {
                    from { opacity: 0; transform: translateY(-10px); }
                    to { opacity: 1; transform: translateY(0); }
                }
                
                @media (max-width: 640px) {
                    .login-card {
                        padding: 24px;
                    }
                }
            `}</style>
        </div>
    );
};

export default Login;

// angular/auth-angular/src/app/components/auth/login/login.component.ts
import {Component, OnInit} from '@angular/core';
import {AuthService} from '../auth.service';
import {Router, RouterLink} from '@angular/router';
import {FormBuilder, FormGroup, ReactiveFormsModule, Validators} from '@angular/forms';
import {LoginRequest} from '../../../types';
import {MatCard, MatCardContent, MatCardHeader} from '@angular/material/card';
import {MatError, MatFormField, MatInput, MatLabel} from '@angular/material/input';
import {NgIf} from '@angular/common';
import {MatButton, MatIconButton} from '@angular/material/button';

@Component({
  selector: 'app-login',
  imports: [
    MatCard,
    ReactiveFormsModule,
    MatFormField,
    MatLabel,
    MatInput,
    MatError,
    MatFormField,
    NgIf,
    MatIconButton,
    MatButton,
    RouterLink,
  ],
  templateUrl: './login.component.html',
  styleUrl: '../auth.component.css',
})
export class LoginComponent implements OnInit{

  protected loginForm: FormGroup = new FormGroup({});
  protected errorMessage: string | null = null;

  constructor(private authService: AuthService , private fb : FormBuilder ,private router : Router) {
  }

  ngOnInit() {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required]],
    })
  }

  onLogin(): void {
    if (this.loginForm.invalid) {
      return;
    }

    const credentials = this.loginForm.value as LoginRequest;
    this.authService.login(credentials).subscribe({
      next: () => {
        this.errorMessage = null;
      },
      error: (err) => {
        this.errorMessage = err.message || 'Login failed. Please try again.';
      },
    });
  }


}

<style>
  .login-container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    background: linear-gradient(140deg, #f6f9fc 0%, #eef1f5 100%);
    font-family: 'Inter', sans-serif;
  }

  .login-card {
    display: flex;
    flex-direction: column;
    padding: 40px;
    border-radius: 10px;
    box-shadow: 0 10px 40px rgba(0, 0, 0, 0.08);
    background-color: white;
    max-width: 400px;
    width: 90%;
    position: relative;
    overflow: hidden;
  }

  .login-card::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 5px;
    background: linear-gradient(90deg, #3182ce, #63b3ed);
  }

  .header {
    display: flex;
    justify-content: center;
    padding: 10px 0 25px 0;
  }

  .header img {
    max-height: 60px;
  }

  .content {
    padding: 10px 0;
  }

  .title {
    color: #2d3748;
    font-size: 24px;
    font-weight: 700;
    text-align: center;
    margin-bottom: 30px;
  }

  .subtitle {
    color: #718096;
    font-size: 15px;
    text-align: center;
    margin-bottom: 30px;
    margin-top: -20px;
  }

  .full-width {
    width: 100%;
    margin-bottom: 20px;
  }

  .button-container {
    display: flex;
    justify-content: center;
    margin: 30px 0 15px 0;
  }

  .button-container button {
    width: 100%;
    padding: 12px 0;
    border-radius: 6px;
    font-weight: 600;
    font-size: 15px;
    background-color: #3182ce;
    color: white;
    border: none;
    transition: all 0.2s ease;
    cursor: pointer;
    box-shadow: 0 4px 6px rgba(49, 130, 206, 0.15);
  }

  .button-container button:hover:not([disabled]) {
    background-color: #2b6cb0;
    box-shadow: 0 6px 12px rgba(49, 130, 206, 0.2);
  }

  .button-container button[disabled] {
    background-color: #e2e8f0;
    color: #a0aec0;
    cursor: not-allowed;
    box-shadow: none;
  }

  .alert {
    background-color: #fff5f5;
    color: #e53e3e;
    padding: 14px 16px;
    border-radius: 6px;
    margin-bottom: 25px;
    font-size: 14px;
    display: flex;
    align-items: center;
    border: 1px solid #fed7d7;
  }

  .alert::before {
    content: "⚠️";
    margin-right: 10px;
    font-size: 16px;
  }

  .redirect-link {
    text-align: center;
    margin-top: 25px;
    font-size: 14px;
    color: #718096;
  }

  .redirect-link a {
    color: #3182ce;
    text-decoration: none;
    font-weight: 500;
    transition: color 0.2s ease;
  }

  .redirect-link a:hover {
    color: #2b6cb0;
    text-decoration: underline;
  }

  /* Customize Material form fields */
  ::ng-deep .mat-form-field-appearance-outline .mat-form-field-outline {
    color: #e2e8f0;
  }

  ::ng-deep .mat-form-field-appearance-outline.mat-focused .mat-form-field-outline-thick {
    color: #3182ce;
  }

  ::ng-deep .mat-form-field-appearance-outline .mat-form-field-label {
    color: #718096;
  }

  ::ng-deep .mat-form-field.mat-focused .mat-form-field-label {
    color: #3182ce;
  }

  ::ng-deep .mat-input-element {
    color: #2d3748;
  }

  ::ng-deep .mat-form-field-appearance-outline .mat-form-field-infix {
    padding: 14px 0;
  }
</style>

<div class="login-container">
  <div class="login-card">
    <div class="header">
      <img src="/app/assets/images/logo.png" alt="app logo">
    </div>
    <div class="content">
      <h1 class="title">Welcome Back</h1>
      <p class="subtitle">Sign in to your account</p>
      <div class="alert" *ngIf="errorMessage">{{ errorMessage }}</div>
      <form [formGroup]="loginForm" (ngSubmit)="onLogin()">
        <mat-form-field appearance="outline" class="full-width">
          <mat-label>Email</mat-label>
          <input matInput
                 placeholder="Enter your email"
                 formControlName="email"
                 required>
          <mat-error *ngIf="loginForm.get('email')?.hasError('required')">
            Email is required
          </mat-error>
          <mat-error *ngIf="loginForm.get('email')?.hasError('email')">
            Email format not valid
          </mat-error>
        </mat-form-field>

        <mat-form-field appearance="outline" class="full-width">
          <mat-label>Password</mat-label>
          <input matInput
                 type="password"
                 formControlName="password"
                 required>
          <button mat-icon-button matSuffix>
          </button>
          <mat-error *ngIf="loginForm.get('password')?.hasError('required')">
            Password is required
          </mat-error>
        </mat-form-field>

        <div class="button-container">
          <button mat-raised-button
                  type="submit"
                  [disabled]="loginForm.invalid">
            Sign in
          </button>
        </div>
      </form>
      <div class="redirect-link">
        <a routerLink="/register">Don't have an account? Create one</a>
      </div>
    </div>
  </div>
</div>
